### ISSUE TITLE
地图上有网格线

### ISSUE THREAD

**Issue by RemoteSensingFrank** [slobber/arcgis-4-with-echarts-4#1]
请问一下，我添加代码之后出现了网格线：
![image](https://user-images.githubusercontent.com/25923674/60564229-74fbf980-9d91-11e9-93df-15c0a97e8981.png)
请问如何才能消除那个网格线呢？

**Comment by zhangyugeng** [comment]
> 请问一下，我添加代码之后出现了网格线：
> ![image](https://user-images.githubusercontent.com/25923674/60564229-74fbf980-9d91-11e9-93df-15c0a97e8981.png)
> 请问如何才能消除那个网格线呢？

请问解决了吗？

**Comment by zhangyugeng** [comment]
@RemoteSensingFrank 
请问解决了，网格问题吗？

**Comment by RemoteSensingFrank** [comment]
解决了，是配置的问题，调整echart的配置可以解决

**Comment by zhangyugeng** [comment]
@RemoteSensingFrank 
大概怎么调整，刚才我看了一下。好像没有关于这个配置项的

**Comment by RemoteSensingFrank** [comment]
在源码里面：改具体怎么改我不记得了，不过我有源码可以发给你，你关注一下我，给我邮箱发个邮件我把代码发给你，具体的效果你可以看我的博客：http://wuweiblog.com/2019/07/21/%E9%85%B7%E7%82%AB%E7%9A%84%E5%8A%A8%E6%80%81%E5%9B%BE/

**Comment by RemoteSensingFrank** [comment]
找到了在源码的setCharts 函数中，
有这么一段：
      setCharts: function () {
        if (!this.visible) return;
        if (this.chartOption == null || this.chartOption == 'undefined') return;
        let baseExtent = this.view.extent;
        //判断是否使用了mark类型标签，每次重绘要重新转换地理坐标到屏幕坐标
        //根据地图extent,重绘echarts
        this.chartOption.xAxis = { show: true, min: baseExtent.xmin, max: baseExtent.xmax };
        this.chartOption.yAxis = { show: true, min: baseExtent.ymin, max: baseExtent.ymax };
        this.chart.setOption(this.chartOption);
        this.chartOption.animation = false;
      },
把true改成false就可以了
